In [ ]:
import numpy as np
a = np.arange(1,9,2)
print(a)

[1 3 5 7]


In [ ]:
a = np.reshape(a,(2,2))
print(a)

[[1 3]
 [5 7]]


In [ ]:
a.transpose()

array([[1, 5],
       [3, 7]])

In [ ]:
a.flatten()

array([1, 3, 5, 7])

In [ ]:
b = np.random.randint(0,20,9)
print(b)

[19 16 15  3 11 11  8 12  0]


In [ ]:
print(b.reshape(3,3))

[[19 16 15]
 [ 3 11 11]
 [ 8 12  0]]


In [ ]:
np.mean(b)

np.float64(10.555555555555555)

In [ ]:
s1 = 'hello every one'
s2 = ' iam Nandhu'
np.add(s1,s2)

np.str_('hello every one iam Nandhu')

In [ ]:
s = np.char.upper(s1)
d = np.char.lower(s2)
print(s)
print(d)

HELLO EVERY ONE
 iam nandhu


In [ ]:
np.char.center(s2,20,"*")

array('**** iam Nandhu*****', dtype='<U20')

In [ ]:
np.char.replace(s2,'iam','my self')

array(' my self Nandhu', dtype='<U15')

In [ ]:
import pandas as pd
z = np.random.randint(1,20,9)
# z = np.reshape(z,(3,3))
# print(z)
pd.Series(z)

0    14
1    10
2    13
3     8
4    14
5    13
6     8
7     8
8    10
dtype: int64

In [ ]:
list = [[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]]
df = pd.DataFrame(list)
print(df)

   0  1  2  3  4  5  6  7
0  1  2  3  4  5  6  7  8
1  8  7  6  5  4  3  2  1


In [ ]:
 b = [{'a':15, 'b':7, 'c':12, 'd':2},
      {'a':5, 'b':7, 'c':12, 'd':22}]
df = pd.DataFrame(b)
print(df)

    a  b   c   d
0  15  7  12   2
1   5  7  12  22


In [ ]:
import pandas as pd
from pandas import DataFrame
b = {'RollNo':pd.Series([1,2,3,4,5]),
     'Maths':pd.Series([55,66,77,98,36]),
     'English':pd.Series([55,66,77,98,36]),
     'Science':pd.Series([55,66,77,98,36])}

df = DataFrame(b)
print(df)

   RollNo  Maths  English  Science
0       1     55       55       55
1       2     66       66       66
2       3     77       77       77
3       4     98       98       98
4       5     36       36       36


In [ ]:
data = pd.read_csv('/content/sample_data/california_housing_test.csv')

data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [ ]:
df.shape

(5, 4)

In [ ]:
df.size

20

In [ ]:
df.head(2)

RollNo  Maths  English  Science
0       1     55       55       55
1       2     66       66       66

In [ ]:
df.tail(2)

RollNo  Maths  English  Science
3       4     98       98       98
4       5     36       36       36

In [ ]:
df.describe()

RollNo      Maths    English    Science
count  5.000000   5.000000   5.000000   5.000000
mean   3.000000  66.400000  66.400000  66.400000
std    1.581139  23.265855  23.265855  23.265855
min    1.000000  36.000000  36.000000  36.000000
25%    2.000000  55.000000  55.000000  55.000000
50%    3.000000  66.000000  66.000000  66.000000
75%    4.000000  77.000000  77.000000  77.000000
max    5.000000  98.000000  98.000000  98.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   RollNo   5 non-null      int64
 1   Maths    5 non-null      int64
 2   English  5 non-null      int64
 3   Science  5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes


In [ ]:
data.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [ ]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
import pandas as pd
df = pd.read_csv('/content/large_sample_with_nulls.csv')
print(df)

    CustomerID           Name   Age  Gender                Email  \
0         1001  Michael Brown  45.0    Male                  NaN   
1         1002  Alice Johnson  25.0    Male    emily@example.com   
2         1003    Emily Davis  25.0  Female    alice@example.com   
3         1004  Alice Johnson  25.0    Male     john@example.com   
4         1005  Alice Johnson  25.0  Female  michael@example.com   
..         ...            ...   ...     ...                  ...   
95        1096  Michael Brown  35.0    Male    alice@example.com   
96        1097  Michael Brown  30.0  Female  michael@example.com   
97        1098  Alice Johnson  40.0  Female     john@example.com   
98        1099       John Doe  35.0  Female                  NaN   
99        1100  Alice Johnson   NaN  Female                  NaN   

    PurchaseAmount    Country  
0           250.00         UK  
1           200.75  Australia  
2           250.00         UK  
3           150.50         UK  
4           150.50     

In [ ]:
df.isnull()

CustomerID   Name    Age  Gender  Email  PurchaseAmount  Country
0        False  False  False   False   True           False    False
1        False  False  False   False  False           False    False
2        False  False  False   False  False           False    False
3        False  False  False   False  False           False    False
4        False  False  False   False  False           False    False
..         ...    ...    ...     ...    ...             ...      ...
95       False  False  False   False  False           False    False
96       False  False  False   False  False           False    False
97       False  False  False   False  False            True     True
98       False  False  False   False   True           False     True
99       False  False   True   False   True           False    False

[100 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   CustomerID      100 non-null    int64  
 1   Name            83 non-null     object 
 2   Age             85 non-null     float64
 3   Gender          66 non-null     object 
 4   Email           80 non-null     object 
 5   PurchaseAmount  79 non-null     float64
 6   Country         80 non-null     object 
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB


In [ ]:
df.isnull().sum()

CustomerID         0
Name              17
Age               15
Gender            34
Email             20
PurchaseAmount    21
Country           20
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(127)

In [ ]:
df.shape

(100, 7)

In [ ]:
df2 = df.dropna()
df2

CustomerID           Name   Age  Gender                Email  \
1         1002  Alice Johnson  25.0    Male    emily@example.com   
2         1003    Emily Davis  25.0  Female    alice@example.com   
3         1004  Alice Johnson  25.0    Male     john@example.com   
4         1005  Alice Johnson  25.0  Female  michael@example.com   
10        1011  Michael Brown  35.0    Male  michael@example.com   
15        1016  Michael Brown  30.0  Female    emily@example.com   
23        1024     Jane Smith  45.0  Female    alice@example.com   
27        1028       John Doe  35.0  Female    emily@example.com   
38        1039  Michael Brown  35.0  Female  michael@example.com   
41        1042    Emily Davis  30.0    Male     john@example.com   
45        1046       John Doe  25.0    Male    alice@example.com   
54        1055     Jane Smith  40.0    Male     john@example.com   
57        1058  Michael Brown  35.0  Female    emily@example.com   
61        1062  Alice Johnson  30.0    Male    alice@example.com   
62        1063    Emily Davis  45.0  Female    alice@example.com   
65        1066  Michael Brown  45.0  Female     jane@example.com   
75        1076  Alice Johnson  30.0    Male    emily@example.com   
76        1077     Jane Smith  40.0    Male     jane@example.com   
79        1080     Jane Smith  25.0    Male     john@example.com   
80        1081     Jane Smith  25.0    Male     john@example.com   
85        1086  Michael Brown  40.0    Male     jane@example.com   
91        1092  Alice Johnson  25.0  Female  michael@example.com   
94        1095  Michael Brown  25.0    Male  michael@example.com   
95        1096  Michael Brown  35.0    Male    alice@example.com   
96        1097  Michael Brown  30.0  Female  michael@example.com   

    PurchaseAmount    Country  
1           200.75  Australia  
2           250.00         UK  
3           150.50         UK  
4           150.50     Canada  
10          300.25         UK  
15          100.00  Australia  
23          100.00     Canada  
27          250.00        USA  
38          250.00         UK  
41          200.75         UK  
45          150.50         UK  
54          100.00     Canada  
57          100.00        USA  
61          100.00  Australia  
62          300.25         UK  
65          300.25     Canada  
75          100.00        USA  
76          300.25     Canada  
79          300.25        USA  
80          100.00  Australia  
85          300.25        USA  
91          100.00  Australia  
94          300.25  Australia  
95          150.50     Canada  
96          150.50         UK

In [ ]:
df3 = df.dropna(axis=1)
df3

CustomerID
0         1001
1         1002
2         1003
3         1004
4         1005
..         ...
95        1096
96        1097
97        1098
98        1099
99        1100

[100 rows x 1 columns]

In [ ]:
df.dropna(axis=0)

CustomerID           Name   Age  Gender                Email  \
1         1002  Alice Johnson  25.0    Male    emily@example.com   
2         1003    Emily Davis  25.0  Female    alice@example.com   
3         1004  Alice Johnson  25.0    Male     john@example.com   
4         1005  Alice Johnson  25.0  Female  michael@example.com   
10        1011  Michael Brown  35.0    Male  michael@example.com   
15        1016  Michael Brown  30.0  Female    emily@example.com   
23        1024     Jane Smith  45.0  Female    alice@example.com   
27        1028       John Doe  35.0  Female    emily@example.com   
38        1039  Michael Brown  35.0  Female  michael@example.com   
41        1042    Emily Davis  30.0    Male     john@example.com   
45        1046       John Doe  25.0    Male    alice@example.com   
54        1055     Jane Smith  40.0    Male     john@example.com   
57        1058  Michael Brown  35.0  Female    emily@example.com   
61        1062  Alice Johnson  30.0    Male    alice@example.com   
62        1063    Emily Davis  45.0  Female    alice@example.com   
65        1066  Michael Brown  45.0  Female     jane@example.com   
75        1076  Alice Johnson  30.0    Male    emily@example.com   
76        1077     Jane Smith  40.0    Male     jane@example.com   
79        1080     Jane Smith  25.0    Male     john@example.com   
80        1081     Jane Smith  25.0    Male     john@example.com   
85        1086  Michael Brown  40.0    Male     jane@example.com   
91        1092  Alice Johnson  25.0  Female  michael@example.com   
94        1095  Michael Brown  25.0    Male  michael@example.com   
95        1096  Michael Brown  35.0    Male    alice@example.com   
96        1097  Michael Brown  30.0  Female  michael@example.com   

    PurchaseAmount    Country  
1           200.75  Australia  
2           250.00         UK  
3           150.50         UK  
4           150.50     Canada  
10          300.25         UK  
15          100.00  Australia  
23          100.00     Canada  
27          250.00        USA  
38          250.00         UK  
41          200.75         UK  
45          150.50         UK  
54          100.00     Canada  
57          100.00        USA  
61          100.00  Australia  
62          300.25         UK  
65          300.25     Canada  
75          100.00        USA  
76          300.25     Canada  
79          300.25        USA  
80          100.00  Australia  
85          300.25        USA  
91          100.00  Australia  
94          300.25  Australia  
95          150.50     Canada  
96          150.50         UK

In [34]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/student_marks_with_nulls.csv')
print(df)

    Roll No     Name  Maths  Science  English
0       101   Anjali   94.0    100.0     90.0
1       102     Ravi   75.0      NaN     77.0
2       103    Meera   99.0     72.0     72.0
3       104    Arjun   90.0     84.0     56.0
4       105    Sneha   85.0     72.0     89.0
5       106    Karan   72.0     95.0     76.0
6       107    Priya   61.0      NaN     69.0
7       108   Vikram    NaN     72.0     50.0
8       109     Nina   74.0      NaN     95.0
9       110    Rohit   89.0     58.0      NaN
10      111    Divya   97.0     90.0      NaN
11      112     Amit   59.0     97.0     56.0
12      113     Tina   81.0      NaN     67.0
13      114    Manoj   92.0     60.0     50.0
14      115     Neha   52.0     87.0     52.0
15      116    Suraj    NaN     85.0      NaN
16      117    Kavya   67.0     99.0     61.0
17      118   Rakesh   74.0    100.0     70.0
18      119    Pooja   76.0      NaN     82.0
19      120   Nikhil    NaN     88.0     97.0
20      121     Isha   92.0     83

In [35]:
df.isnull().sum().sum()

np.int64(18)

In [49]:
df.fillna(method='ffill')

<ipython-input-49-5c0beae7dc1e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


Roll No     Name  Maths  Science  English
0       101   Anjali   94.0    100.0     90.0
1       102     Ravi   75.0    100.0     77.0
2       103    Meera   99.0     72.0     72.0
3       104    Arjun   90.0     84.0     56.0
4       105    Sneha   85.0     72.0     89.0
5       106    Karan   72.0     95.0     76.0
6       107    Priya   61.0     95.0     69.0
7       108   Vikram   61.0     72.0     50.0
8       109     Nina   74.0     72.0     95.0
9       110    Rohit   89.0     58.0     95.0
10      111    Divya   97.0     90.0     95.0
11      112     Amit   59.0     97.0     56.0
12      113     Tina   81.0     97.0     67.0
13      114    Manoj   92.0     60.0     50.0
14      115     Neha   52.0     87.0     52.0
15      116    Suraj   52.0     85.0     52.0
16      117    Kavya   67.0     99.0     61.0
17      118   Rakesh   74.0    100.0     70.0
18      119    Pooja   76.0    100.0     82.0
19      120   Nikhil   76.0     88.0     97.0
20      121     Isha   92.0     83.0     97.0
21      122   Deepak   92.0     89.0     53.0
22      123    Reema   79.0     92.0     51.0
23      124    Harsh   86.0     70.0     51.0
24      125  Lakshmi  100.0     70.0     51.0
25      126    Rahul   59.0     80.0     97.0
26      127     Sara   75.0     99.0     78.0
27      128     Yash   75.0     67.0     57.0
28      129     Alok   75.0     85.0     91.0
29      130     Ritu   66.0     97.0     96.0

In [52]:
df['English'].fillna(value=df['English'].mean())

0     90.000000
1     77.000000
2     72.000000
3     56.000000
4     89.000000
5     76.000000
6     69.000000
7     50.000000
8     95.000000
9     72.166667
10    72.166667
11    56.000000
12    67.000000
13    50.000000
14    52.000000
15    72.166667
16    61.000000
17    70.000000
18    82.000000
19    97.000000
20    72.166667
21    53.000000
22    51.000000
23    72.166667
24    72.166667
25    97.000000
26    78.000000
27    57.000000
28    91.000000
29    96.000000
Name: English, dtype: float64

In [60]:
df.tail(9)

Roll No     Name  Maths  Science  English
21      122   Deepak    NaN     89.0     53.0
22      123    Reema   79.0     92.0     51.0
23      124    Harsh   86.0     70.0      NaN
24      125  Lakshmi  100.0      NaN      NaN
25      126    Rahul   59.0     80.0     97.0
26      127     Sara   75.0     99.0     78.0
27      128     Yash    NaN     67.0     57.0
28      129     Alok    NaN     85.0     91.0
29      130     Ritu   66.0     97.0     96.0

In [74]:
df['Maths'].replace('[A-Za-z]',0,regex=True)

<ipython-input-74-2f06a32525f8>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Maths'].replace('[A-Za-z]',0,regex=True)


0      94.0
1      75.0
2      99.0
3       0.0
4      85.0
5       0.0
6      61.0
7       0.0
8      74.0
9      89.0
10     97.0
11     59.0
12     81.0
13     92.0
14     52.0
15      0.0
16     67.0
17     74.0
18     76.0
19      0.0
20     92.0
21      0.0
22     79.0
23     86.0
24    100.0
25     59.0
26     75.0
27      0.0
28      0.0
29     66.0
Name: Maths, dtype: float64

In [75]:
df= pd.read_csv('/content/student_marks_with_nulls.csv')
df

Roll No     Name  Maths  Science  English
0       101   Anjali   94.0    100.0     90.0
1       102     Ravi   75.0      NaN     77.0
2       103    Meera   99.0     72.0     72.0
3       104    Arjun   90.0     84.0     56.0
4       105    Sneha   85.0     72.0     89.0
5       106    Karan   72.0     95.0     76.0
6       107    Priya   61.0      NaN     69.0
7       108   Vikram    NaN     72.0     50.0
8       109     Nina   74.0      NaN     95.0
9       110    Rohit   89.0     58.0      NaN
10      111    Divya   97.0     90.0      NaN
11      112     Amit   59.0     97.0     56.0
12      113     Tina   81.0      NaN     67.0
13      114    Manoj   92.0     60.0     50.0
14      115     Neha   52.0     87.0     52.0
15      116    Suraj    NaN     85.0      NaN
16      117    Kavya   67.0     99.0     61.0
17      118   Rakesh   74.0    100.0     70.0
18      119    Pooja   76.0      NaN     82.0
19      120   Nikhil    NaN     88.0     97.0
20      121     Isha   92.0     83.0      NaN
21      122   Deepak    NaN     89.0     53.0
22      123    Reema   79.0     92.0     51.0
23      124    Harsh   86.0     70.0      NaN
24      125  Lakshmi  100.0      NaN      NaN
25      126    Rahul   59.0     80.0     97.0
26      127     Sara   75.0     99.0     78.0
27      128     Yash    NaN     67.0     57.0
28      129     Alok    NaN     85.0     91.0
29      130     Ritu   66.0     97.0     96.0

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Roll No'].plot(kind='hist', bins=20, title='Roll No')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Maths'].plot(kind='hist', bins=20, title='Maths')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Science'].plot(kind='hist', bins=20, title='Science')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='Roll No', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Roll No', y='Maths', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Maths', y='Science', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Science', y='English', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Maths']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Maths')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Science']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Science')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['English']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('English')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['Roll No'].plot(kind='line', figsize=(8, 4), title='Roll No')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Maths'].plot(kind='line', figsize=(8, 4), title='Maths')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Science'].plot(kind='line', figsize=(8, 4), title='Science')
plt.gca().spines[['top', 'right']].set_visible(False)

In [81]:
df.loc[1:4]

Roll No   Name  Maths  Science  English
1      102   Ravi   75.0      NaN     77.0
2      103  Meera   99.0     72.0     72.0
3      104  Arjun   90.0     84.0     56.0
4      105  Sneha   85.0     72.0     89.0

In [90]:
  df.loc[df['Maths'] < 80,['English']]

English
1      77.0
5      76.0
6      69.0
8      95.0
11     56.0
14     52.0
16     61.0
17     70.0
18     82.0
22     51.0
25     97.0
26     78.0
29     96.0

In [96]:
df.iloc[1:5,1]

1     Ravi
2    Meera
3    Arjun
4    Sneha
Name: Name, dtype: object

In [102]:
bg = df.groupby(by='Name')
print(bg)

In [103]:
bg.groups

{'Alok': [28], 'Amit': [11], 'Anjali': [0], 'Arjun': [3], 'Deepak': [21], 'Divya': [10], 'Harsh': [23], 'Isha': [20], 'Karan': [5], 'Kavya': [16], 'Lakshmi': [24], 'Manoj': [13], 'Meera': [2], 'Neha': [14], 'Nikhil': [19], 'Nina': [8], 'Pooja': [18], 'Priya': [6], 'Rahul': [25], 'Rakesh': [17], 'Ravi': [1], 'Reema': [22], 'Ritu': [29], 'Rohit': [9], 'Sara': [26], 'Sneha': [4], 'Suraj': [15], 'Tina': [12], 'Vikram': [7], 'Yash': [27]}

In [106]:
data1 =pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
})
data1

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [107]:
data2 = {
    'Product': ['Laptop', 'Tablet', 'Smartphone'],
    'Price': [1200, 600, 800],
    'Quantity': [5, 10, 8]
}
data2 = pd.DataFrame(data2)
data2

Product  Price  Quantity
0      Laptop   1200         5
1      Tablet    600        10
2  Smartphone    800         8

In [113]:
pd.merge(data1,data2,left_index=True,right_index=True)

Name  Age         City     Product  Price  Quantity
0    Alice   25     New York      Laptop   1200         5
1      Bob   30  Los Angeles      Tablet    600        10
2  Charlie   35      Chicago  Smartphone    800         8

In [110]:
# Correct the function name from mearge to merge and use left_index and right_index to merge on the index
pd.merge(data1,data2,left_index=True, right_index=True)

Name  Age         City     Product  Price  Quantity
0    Alice   25     New York      Laptop   1200         5
1      Bob   30  Los Angeles      Tablet    600        10
2  Charlie   35      Chicago  Smartphone    800         8

In [115]:
course_data = {
    'Enrollment_ID': [201, 202, 203, 204, 205],
    'Student_ID': [101, 102, 103, 104, 105],
    'Course': ['Data Structures', 'Calculus II', 'Quantum Mechanics', 'Genetics', 'Shakespeare'],
    'Credits': [3, 4, 4, 3, 3]
}
cd1 = pd.DataFrame(course_data)
cd1

Enrollment_ID  Student_ID             Course  Credits
0            201         101    Data Structures        3
1            202         102        Calculus II        4
2            203         103  Quantum Mechanics        4
3            204         104           Genetics        3
4            205         105        Shakespeare        3

In [119]:
student_data = {
    'Student_ID': [106, 107,108, 109, 110],
    'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Lee', 'Dana White', 'Eva Brown'],
    'Major': ['Computer Science', 'Mathematics', 'Physics', 'Biology', 'English'],
    'GPA': [3.8, 3.5, 3.9, 3.2, 3.6]
}
cd2 = pd.DataFrame(student_data)
cd2

Student_ID         Name             Major  GPA
0         106  Alice Smith  Computer Science  3.8
1         107  Bob Johnson       Mathematics  3.5
2         108  Charlie Lee           Physics  3.9
3         109   Dana White           Biology  3.2
4         110    Eva Brown           English  3.6

In [122]:
pd.merge(cd1,cd2,how ='left')

Enrollment_ID  Student_ID             Course  Credits Name Major  GPA
0            201         101    Data Structures        3  NaN   NaN  NaN
1            202         102        Calculus II        4  NaN   NaN  NaN
2            203         103  Quantum Mechanics        4  NaN   NaN  NaN
3            204         104           Genetics        3  NaN   NaN  NaN
4            205         105        Shakespeare        3  NaN   NaN  NaN

In [128]:
students_df1 = pd.DataFrame({
    'Student_ID': [101, 102, 103],
    'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Lee'],
    'Major': ['Computer Science', 'Mathematics', 'Physics'],
    'GPA': [3.8, 3.5, 3.9]
})
sd1 = pd.DataFrame(students_df1)
sd1

Student_ID         Name             Major  GPA
0         101  Alice Smith  Computer Science  3.8
1         102  Bob Johnson       Mathematics  3.5
2         103  Charlie Lee           Physics  3.9

In [126]:
students_df2 = pd.DataFrame({
    'Student_ID': [104, 105, 106],
    'Name': ['Dana White', 'Eva Brown', 'Frank Green'],
    'Major': ['Biology', 'English', 'Economics'],
    'GPA': [3.2, 3.6, 3.7]
})
sd2= pd.DataFrame(students_df2)
sd2

Student_ID         Name      Major  GPA
0         104   Dana White    Biology  3.2
1         105    Eva Brown    English  3.6
2         106  Frank Green  Economics  3.7

In [136]:
pd.concat([sd1,sd2],ignore_index= True)

Student_ID         Name             Major  GPA
0         101  Alice Smith  Computer Science  3.8
1         102  Bob Johnson       Mathematics  3.5
2         103  Charlie Lee           Physics  3.9
3         104   Dana White           Biology  3.2
4         105    Eva Brown           English  3.6
5         106  Frank Green         Economics  3.7